[Main]
name   = "Floral Daydream"
mode   = "light"
author = "Myian"

[Base]
base    = "#fff2f6"
default = "#77596e"
faded   = "#b396a5"
red     = "#ee6991"
orange  = "#e97c4a"
yellow  = "#cca333"
green   = "#418f57"
cyan    = "#47aab1"
blue    = "#5183cf"
purple  = "#9b68d4"

[Project]
root     = "default"
folder   = "yellow"
file     = "orange"
title    = "blue"
chapter  = "purple"
scene    = "red"
note     = "#6dad7f"
active   = "#6dad7f"
inactive = "faded"
disabled = "#ccb5c1"

[Icon]
tool      = "default"
sidebar   = "#e94e7c"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "default"
markdown  = "orange"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "#ffd5dd"
windowText      = "default:D120"
base            = "base"
alternateBase   = "#ffb6cc"
text            = "default"
tooltipBase     = "#fff0b9"
tooltipText     = "default:D120"
button          = "base"
buttonText      = "default:D120"
brightText      = "base"
highlight       = "#fc7fa4"
highlightedText = "#ffffff"
link            = "blue"
linkVisited     = "blue"
accent          = "#ff709b"

[GUI]
helpText     = "default"
fadedText    = "faded"
errorText    = "red"
accentText   = "red"
activeButton = "red:128"
activeBase   = "base"
searchMatch  = "#fc7fa47f"

[Syntax]
background     = "base"
text           = "default"
line           = "#ffdbe4"
link           = "blue"
headerText     = "blue"
headerTag      = "blue:128"
emphasis       = "#8152b8"
whitespace     = "blue:80"
dialog         = "#db456b"
altDialog      = "blue"
note           = "green"
hidden         = "faded"
shortcode      = "green"
keyword        = "blue"
tag            = "green"
value          = "orange"
optional       = "faded"
spellCheckLine = "#ff0000"
errorLine      = "green"
replaceTag     = "green"
modifier       = "blue"
textHighlight  = "green:64"
