[Main]
name   = "Friendly Autumn"
mode   = "light"
author = "Myian"

[Base]
base    = "#f3ece5"
default = "#867182"
faded   = "#aa9ca5"
red     = "#e06d7d"
orange  = "#d37c5a"
yellow  = "#d3a35b"
green   = "#639b42"
cyan    = "#4aac93"
blue    = "#5791c4"
purple  = "#b868b1"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "green"
inactive = "faded"
disabled = "faded:L120"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "green"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#ebdac6"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#eecfa9"
highlightedText = "default:D120"
link            = "blue"
linkVisited     = "blue"
accent          = "#e0ab88"

[GUI]
helpText     = "default:L110"
fadedText    = "faded"
errorText    = "red"
accentText   = "orange"
activeButton = "orange:96"
activeBase   = "#fdfbf8"
searchMatch  = "green:80"

[Syntax]
background     = "#fdfaf7"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "#c5965d"
headerTag      = "#eecfa9"
emphasis       = "purple"
whitespace     = "yellow:80"
dialog         = "orange"
altDialog      = "blue"
note           = "green"
hidden         = "faded"
shortcode      = "green"
keyword        = "#c54e68"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "blue"
modifier       = "#3c8b3c"
textHighlight  = "yellow:64"
