[Main]
name   = "Friendly Winter"
mode   = "light"
author = "Myian"

[Base]
base    = "#e5eff3"
default = "#697281"
faded   = "#919eac"
red     = "#d17a86"
orange  = "#c5856c"
yellow  = "#bea550"
green   = "#609173"
cyan    = "#67c5bd"
blue    = "#5a95b1"
purple  = "#c076ba"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "green"
inactive = "faded"
disabled = "faded:L120"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "purple"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#cbe7ee"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#b3e4f0"
highlightedText = "default:D120"
link            = "blue"
linkVisited     = "blue"
accent          = "#87cfe0"

[GUI]
helpText     = "default:L110"
fadedText    = "faded"
errorText    = "red"
accentText   = "blue"
activeButton = "blue:64"
activeBase   = "#f7fbfd"
searchMatch  = "purple:80"

[Syntax]
background     = "#f8fdff"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "blue"
headerTag      = "blue:128"
emphasis       = "blue"
whitespace     = "blue:80"
dialog         = "green"
altDialog      = "orange"
note           = "purple"
hidden         = "faded"
shortcode      = "purple"
keyword        = "#bb5a6f"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "orange"
modifier       = "#9d68aa"
textHighlight  = "blue:64"
