[Main]
name   = "Friendly Spring"
mode   = "light"
author = "Myian"

[Base]
base    = "#faecef"
default = "#756e83"
faded   = "#a397a7"
red     = "#e06d7d"
orange  = "#d68463"
yellow  = "#d3a35b"
green   = "#509b66"
cyan    = "#48a599"
blue    = "#5791c4"
purple  = "#bb6dae"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "green"
inactive = "faded"
disabled = "faded:L120"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "orange"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#fad2dc"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#ffbfce"
highlightedText = "default:D120"
link            = "blue"
linkVisited     = "blue"
accent          = "#ffa6bb"

[GUI]
helpText     = "default:L110"
fadedText    = "faded"
errorText    = "red"
accentText   = "red"
activeButton = "red:96"
activeBase   = "#fdf5f7"
searchMatch  = "orange:80"

[Syntax]
background     = "#fef8f9"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "red"
headerTag      = "red:128"
emphasis       = "blue"
whitespace     = "red:80"
dialog         = "green"
altDialog      = "purple"
note           = "orange"
hidden         = "faded"
shortcode      = "orange"
keyword        = "#c54e68"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "purple"
modifier       = "#b4654d"
textHighlight  = "red:64"
