[Main]
name   = "Dark Arts"
mode   = "dark"
author = "Myian"

[Base]
base    = "#211d24"
default = "#ddcac1"
faded   = "#776c79"
red     = "#da7676"
orange  = "#df936f"
yellow  = "#ebc089"
green   = "#7aa079"
cyan    = "#76b49f"
blue    = "#7195ad"
purple  = "#8f77af"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "green"
scene    = "blue"
note     = "red"
active   = "default"
inactive = "faded"
disabled = "faded:D150"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "yellow"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#342f38"
text            = "default"
tooltipBase     = "default"
tooltipText     = "base"
button          = "base:L125"
buttonText      = "default"
brightText      = "base"
highlight       = "#4e476b"
highlightedText = "#ece1dc"
link            = "blue"
linkVisited     = "blue"
accent          = "#8f6476"

[GUI]
helpText     = "faded:L125"
fadedText    = "faded"
errorText    = "red"
accentText   = "#c99fb0"
activeButton = "base:L200"
activeBase   = "#342f38"
searchMatch  = "red:80"

[Syntax]
background     = "base:D135"
text           = "default"
line           = "#29263c"
link           = "blue"
headerText     = "#948abb"
headerTag      = "#948abb80"
emphasis       = "green"
whitespace     = "blue:96"
dialog         = "#aa7f91"
altDialog      = "orange"
note           = "yellow"
hidden         = "faded"
shortcode      = "yellow"
keyword        = "#b6525a"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "blue"
modifier       = "#a07857"
textHighlight  = "#3c3958"
