[Main]
name   = "Friendly Summer"
mode   = "light"
author = "Myian"

[Base]
base    = "#ebf0e1"
default = "#73757e"
faded   = "#9b98a5"
red     = "#e06d7d"
orange  = "#d37c5a"
yellow  = "#d3a35b"
green   = "#639b42"
cyan    = "#4aac93"
blue    = "#5791c4"
purple  = "#b868b1"

[Project]
root     = "default"
folder   = "yellow"
file     = "default"
title    = "purple"
chapter  = "blue"
scene    = "green"
note     = "red"
active   = "green"
inactive = "faded"
disabled = "faded:L120"

[Icon]
tool      = "default"
sidebar   = "default"
accept    = "green"
reject    = "red"
action    = "blue"
option    = "orange"
apply     = "green"
create    = "yellow"
destroy   = "faded"
reset     = "green"
add       = "green"
change    = "green"
remove    = "red"
shortcode = "blue"
markdown  = "default"
system    = "yellow"
info      = "blue"
warning   = "orange"
error     = "red"

[Palette]
window          = "base"
windowText      = "default"
base            = "base"
alternateBase   = "#d0ebc3"
text            = "default"
tooltipBase     = "#ffecad"
tooltipText     = "default"
button          = "base"
buttonText      = "default"
brightText      = "base"
highlight       = "#b6e2a0"
highlightedText = "default:D120"
link            = "blue"
linkVisited     = "blue"
accent          = "#aad686"

[GUI]
helpText     = "default:L110"
fadedText    = "faded"
errorText    = "red"
accentText   = "green"
activeButton = "green:64"
activeBase   = "#f9fdf7"
searchMatch  = "blue:80"

[Syntax]
background     = "#fdfefb"
text           = "default"
line           = "base"
link           = "blue"
headerText     = "green"
headerTag      = "green:128"
emphasis       = "#b98c55"
whitespace     = "green:64"
dialog         = "green"
altDialog      = "purple"
note           = "blue"
hidden         = "faded"
shortcode      = "blue"
keyword        = "#c54e68"
tag            = "red"
value          = "faded"
optional       = "faded"
spellCheckLine = "red"
errorLine      = "blue"
replaceTag     = "purple"
modifier       = "#496fa1"
textHighlight  = "green:64"
