name: Build Windows

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/part_assets.yml
    with:
      icons-free: true
      icons-non-free: true
    permissions:
      contents: read

  buildWin-X64:
    needs: buildAssets
    uses: ./.github/workflows/part_win_x64.yml
    secrets: inherit
    permissions:
      contents: read
