name: Build Linux Images

on: workflow_dispatch

jobs:
  buildAssets:
    uses: ./.github/workflows/part_assets.yml
    with:
      icons-free: true
      icons-non-free: true
    permissions:
      contents: read

  buildLinux-AppImage:
    needs: buildAssets
    uses: ./.github/workflows/part_appimage.yml
    secrets: inherit
    permissions:
      contents: read

  buildLinux-Flatpak:
    needs: buildAssets
    uses: ./.github/workflows/part_flatpak.yml
    secrets: inherit
    permissions:
      contents: read
