name: Build MacOS

on:
  push:
    branches:
      - feat/package-main-macos
  workflow_dispatch:
    inputs:
      configuration:
        description: "Sign and notarise the app"
        type: choice
        options:
          - Debug
          - Release
        default: Debug

jobs:
  buildAssets:
    uses: ./.github/workflows/part_assets.yml
    with:
      icons-free: true
      icons-non-free: true
    permissions:
      contents: read

  buildMac:
    needs: buildAssets
    uses: ./.github/workflows/part_macos.yml
    with:
      configuration: ${{ inputs.configuration || 'Debug' }}
    secrets: inherit
    permissions:
      contents: read
